CREATE TABLE loan_applications (
    id SERIAL PRIMARY KEY,
    Month INT,
    Name TEXT,
    Age INT,
    SSN TEXT,
    Occupation TEXT,
    Annual_Income FLOAT,
    Num_Bank_Accounts INT,
    Num_Credit_Card INT,
    Interest_Rate FLOAT,
    Num_of_Loan INT,
    Type_of_Loan TEXT,
    Delay_from_due_date INT,
    Num_of_Delayed_Payment INT,
    Changed_Credit_Limit FLOAT,
    Num_Credit_Inquiries INT,
    Credit_Mix TEXT,
    Outstanding_Debt FLOAT,
    Credit_Utilization_Ratio FLOAT,
    Payment_of_Min_Amount TEXT,
    Total_EMI_per_month FLOAT,
    Amount_invested_monthly FLOAT,
    Payment_Behaviour TEXT,
    Monthly_Balance FLOAT,
    Credit_History_Years INT,
    Credit_History_Months INT,
    prediction TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

